<x-app-layout>
    @push('css')
        <link href="{{ asset('static/5.60a3b147f091048d9af5.css') }}" rel="stylesheet" type="text/css"/>
    @endpush
    <div class="Pane Pane--underSiteNav Pane--repeat" media-medium="hide"><div class="Pane-bg"><div class="Pane-overlay"></div></div><div class="Pane-content"><div class="contain-small"><div class="contain-masthead"><div class="space-small"></div><div class="font-bliz-light-small-gray">Ошибка 404</div><div class="space-small"></div><div class="font-semp-large-white">Что-то пошло не так...</div></div><div class="space-small"></div><div class="space-small"></div><div class="color-monochrome-white">Профиль этого персонажа не показывается по одной из следующих причин.</div><div class="space-small"></div><div class="color-beige-light"><ul><li>Этот персонаж неактивен. Если это ваш персонаж, попробуйте войти за него в игру и снова выйти.</li><li>Имя персонажа или название игрового мира написано с ошибкой.</li><li>Этот персонаж менял игровой мир или фракцию.</li><li>Возможно, этот персонаж был удален.</li><li>Персонаж не достиг 10-го уровня и не может быть отображен.</li><li>Это иллюзия! Что вы скрываете?</li></ul></div></div><div class="contain-small"><div class="space-small"></div><div class="gutter-small"><div class="Art"><div class="Art-size" style="padding-top:56.25%"></div><div class="Art-image" style="background-image:url({{ asset('cms/template_resource/8L50WSHT3HTA1490910058713.jpg') }});"></div><div class="Art-overlay"></div></div></div><div class="space-large"></div></div></div></div><div class="Pane Pane--underSiteNav Pane--cropFull hide" data-url="{{ asset('cms/template_resource/TDL1G704JK0U1490910060417.jpg') }}" media-medium="!hide"><div class="Pane-bg" style="background-image:url({{ asset('cms/template_resource/TDL1G704JK0U1490910060417.jpg') }});"><div class="Pane-overlay"></div></div><div class="Pane-content"><div class="space-large"></div><div class="gutter-huge"><div class="Box Box--overlayDark align-left contain-small contain-right" media-wide="contain-medium"><div class="gutter-small"><div class="contain-masthead"><div class="space-small"></div><div class="font-bliz-light-small-gray">Ошибка 404</div><div class="space-small"></div><div class="font-semp-large-white">Что-то пошло не так...</div></div><div class="space-small"></div><div class="space-small"></div><div class="color-monochrome-white">Профиль этого персонажа не показывается по одной из следующих причин.</div><div class="space-small"></div><div class="color-beige-light"><ul><li>Этот персонаж неактивен. Если это ваш персонаж, попробуйте войти за него в игру и снова выйти.</li><li>Имя персонажа или название игрового мира написано с ошибкой.</li><li>Этот персонаж менял игровой мир или фракцию.</li><li>Возможно, этот персонаж был удален.</li><li>Персонаж не достиг 10-го уровня и не может быть отображен.</li><li>Это иллюзия! Что вы скрываете?</li></ul></div></div></div></div><div class="space-huge" media-medium="hide" media-wide="!hide"></div><div class="space-huge"></div><div class="space-huge"></div></div></div>

    @push('scripts')
        <script src="{{ asset('static/runtime.c86dff083122a451b1af.js') }}"></script>
        <script src="{{ asset('static/vendor.ac7a75610385e9b40211.js') }}"></script>
        <script src="{{ asset('static/3.20dec79f412b658fa525.js') }}"></script>
        <script src="{{ asset('static/legacy-components.24c8e8ac1040f44e6717.js') }}"></script>
    @endpush
</x-app-layout>

